test:
  eshop:
    ui:
      baseUrl: http://localhost:2102
    api:
      baseUrl: http://localhost:2102
  erp:
    api:
      baseUrl: http://localhost:9104/erp
  clock:
    api:
      baseUrl: http://localhost:9104/clock
