test:
  eshop:
    ui:
      baseUrl: http://localhost:2101
    api:
      baseUrl: http://localhost:2101
  erp:
    api:
      baseUrl: http://localhost:9103/erp
  clock:
    api:
      baseUrl: none
